cors:
  originPatterns: http://localhost:8080,https://teste.com.br
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-with-springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true