server:
  port: 80
cors:
  originPatterns: http://localhost:8080,https://teste.com.br,http://localhost:3000,http://localhost
file:
  upload-dir: /Usuários/T-Gamer/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-with-springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  paths-to-match:
  - /auth/**
  - /api/**/v1/**
  swagger-ui:
    use-root-path: true